// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvuXJ9cgVzmpzHAxTXxovDkCF7Srk5sag',
    appId: '1:429655124846:web:a0e9ce8eb4bc59d5a8ef7f',
    messagingSenderId: '429655124846',
    projectId: 'local-helper-finder-e51fb',
    authDomain: 'local-helper-finder-e51fb.firebaseapp.com',
    storageBucket: 'local-helper-finder-e51fb.firebasestorage.app',
    measurementId: 'G-L11R4H0M7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaF_RGy20o2iKXm9dOz_Ko4v1kp8s1iiI',
    appId: '1:429655124846:android:4d2e843cb7a62f2da8ef7f',
    messagingSenderId: '429655124846',
    projectId: 'local-helper-finder-e51fb',
    storageBucket: 'local-helper-finder-e51fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5J8SmWmazEvNDRAFc8k0CorTG_c9GTAk',
    appId: '1:429655124846:ios:4d4eb23e7744b594a8ef7f',
    messagingSenderId: '429655124846',
    projectId: 'local-helper-finder-e51fb',
    storageBucket: 'local-helper-finder-e51fb.firebasestorage.app',
    iosBundleId: 'com.techneo.locallinker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5J8SmWmazEvNDRAFc8k0CorTG_c9GTAk',
    appId: '1:429655124846:ios:4d4eb23e7744b594a8ef7f',
    messagingSenderId: '429655124846',
    projectId: 'local-helper-finder-e51fb',
    storageBucket: 'local-helper-finder-e51fb.firebasestorage.app',
    iosBundleId: 'com.techneo.locallinker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvuXJ9cgVzmpzHAxTXxovDkCF7Srk5sag',
    appId: '1:429655124846:web:c35f60ce7a5c43f1a8ef7f',
    messagingSenderId: '429655124846',
    projectId: 'local-helper-finder-e51fb',
    authDomain: 'local-helper-finder-e51fb.firebaseapp.com',
    storageBucket: 'local-helper-finder-e51fb.firebasestorage.app',
    measurementId: 'G-LZRW4ZPE2H',
  );
}
